#`version: "3.5"` указывает версию формата файла Docker Compose, который будет использоваться. В данном случае это версия 3.5. Эта версия поддерживает такие возможности, как объекты `config`, `секреты` и опции `deploy` для развертывания сервисов в рое.
version: "3.5"

#Это определение сети под названием "docker_lasp" с именем сети по умолчанию. Эта сеть может использоваться для соединения различных служб, определенных в файле Docker Compose, позволяя им взаимодействовать друг с другом.
networks:
  docker_lasp:
    name: $DEFAULT_NETWORK

services:
  #`zabbix-agent2:` определяет сервис в файле Docker Compose для запуска агента Zabbix версии 2. В нем указывается образ для использования, переменные окружения для установки, ограничения и резервирование ресурсов, порты для открытия и сеть для подключения. Также задается имя контейнера, политика перезапуска и зависимости от других служб.
  zabbix-agent2:
   #Определение ограничений и резервирования ресурсов для службы `zabbix-agent2` в файле Docker Compose. Он ограничивает использование CPU до 0.20 и памяти до 128MB, и резервирует минимум 0.10 CPU и 64MB памяти. Параметр `mode: global` указывает, что служба должна быть развернута на всех узлах роя.
   deploy:
     resources:
       #Установка ограничений на ресурсы для службы `zabbix-agent2` в файле Docker Compose. Он ограничивает использование процессора до 0,20 и памяти до 128 МБ.
       limits:
         cpus: "0.20"
         memory: "128M"
       #`reservations` устанавливает минимальное количество ресурсов CPU и памяти, которые должны быть доступны для работы службы `zabbix-agent2`. В данном случае резервируется минимум 0.10 CPU и 64MB памяти. Это гарантирует, что служба имеет достаточно ресурсов для нормальной работы и не позволяет другим службам использовать все ресурсы на узле.
       reservations:
         cpus: "0.10"
         memory: "64M"
     #`mode: global` устанавливает режим развертывания для сервиса `zabbix-agent2` на global, что означает, что сервис должен быть развернут на всех узлах роя.
     mode: global
   #`env_file: - "zabbix.env"` - это указание пути к файлу окружения, содержащему переменные окружения, которые необходимо установить для службы. Файл `zabbix.env` должен находиться в том же каталоге, что и файл Docker Compose, и будет использоваться для установки переменных окружения для сервисов `zabbix-agent2`, `zabbix-java-gateway` и `zabbix-snmptraps`.
   env_file:
     - "zabbix.env"
   #`image: zabbix/zabbix-agent2:alpine-7.0-latest` указывает образ Docker, который будет использоваться для службы `zabbix-agent2`. Он извлекает образ `zabbix-agent2` из репозитория Docker Hub `zabbix/zabbix-agent2` с тегом `alpine-7.0-latest`. Этот образ основан на дистрибутиве Alpine Linux и включает агент Zabbix версии 2.
   image: zabbix/zabbix-agent2:alpine-7.0-latest
   #`labels` - это раздел в файле Docker Compose, который позволяет вам добавлять метаданные к вашим сервисам. В данном случае секция `labels` добавляет метаданные к службе `zabbix-agent2`. Метки - это пары ключ-значение, которые предоставляют информацию о службе, такую как ее описание, компания, компонент и операционная система. Эти метки можно использовать для фильтрации, поиска и организации сервисов в среде Docker.
   labels:
     - "com.zabbix.description=Zabbix agent 2"
     - "com.zabbix.company=Zabbix LLC"
     - "com.zabbix.component=zabbix-agentd"
     - "com.zabbix.os=linux"
   #`ports: - "10050:10050"` открывает порт 10050 на контейнере для порта 10050 на хост-машине. Это позволяет внешним системам взаимодействовать с агентом Zabbix, запущенным внутри контейнера, через порт 10050.
   ports:
     - "10050:10050"
   #`privileged: true` устанавливает службу `zabbix-agent2` на запуск в привилегированном режиме, что дает контейнеру доступ ко всем устройствам на хост-машине и позволяет выполнять операции, которые обычно не разрешены в контейнере. Это может представлять угрозу безопасности и должно использоваться только в случае необходимости. В данном случае может потребоваться, чтобы агент Zabbix имел доступ к определенным устройствам или выполнял определенные операции, требующие привилегированного доступа.
   privileged: true
   #`restart: always` - это параметр конфигурации в файле Docker Compose, который указывает, что контейнер всегда должен перезапускаться, если он останавливается по какой-либо причине, например, в результате сбоя или ручной остановки. Это гарантирует, что служба всегда работает и доступна, даже в случае сбоя.
   restart: always
   #`container_name: zabbix-agent2` задает имя контейнера, который будет создан для службы `zabbix-agent2`. Это позволяет легко идентифицировать контейнер и управлять им, а также гарантирует, что контейнер будет иметь уникальное имя в среде Docker.
   container_name: zabbix-agent2
   #Раздел `depends_on` в службе `zabbix-agent2` указывает, что служба `zabbix-agent2` зависит от службы `zabbix-server`. Это означает, что служба `zabbix-server` должна быть запущена до запуска службы `zabbix-agent2`. Это гарантирует, что агент Zabbix имеет сервер для подключения и может начать отправлять данные на сервер Zabbix.
   depends_on:
     - "zabbix-server"
   #`networks: - "docker_net"` указывает, что сервисы, определенные в файле Docker Compose, должны быть подключены к сети Docker с именем "docker_net". Это позволяет сервисам взаимодействовать друг с другом по сети и с другими сервисами или контейнерами, подключенными к той же сети.
   networks:
     - "docker_net"
